#SPDX-License-Identifier: MIT-0
---
# tasks file for base
# User creation, switch to jarvis instead of root

- name: Ensure required groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - docker
  become: true

- name: User creation and group assignment
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups:
      - sudo
      - docker
    append: true
  become: true

- name: add ssh_key for connect
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub')}}"
  become: true
#? permet de se connecter a ce user via mon terminal pour le script ansible

- name: Sudo without ask password
  ansible.builtin.copy:
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ deploy_user }}
    owner: root
    group: root
    mode: 0440
  become: true