server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3; 
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    #toute la partie securite, ssl/tls

    root /var/www/wordpress;
    server_name portedesaintcloud.duckdns.org;
    index index.php index.html;

    location / { 
        try_files $uri $uri/ /index.php?$args;
    }
    # voici un url : "https://kjolly.42.fr/mon-article/photo.jpg"
    # voici ce que '$URI' vaut : "/mon-article/photo.jpg"
    # '$URI' essaye de voir si le fichier existe
    # '$URI/' va regarder s'il existe dans un dossier
    # "/index..." envoie la requete a index.php gerer par php-fpm si ni '$URI' ni '$URI/' n'ont trouver

    location ^~ /phpmyadmin/ { # ^~ lui dit de s'arreter et d'appliquer ce block des qu'on entre dans ce cas la
        proxy_pass http://phpmyadmin:80/;
        # https://blog.stephane-robert.info/docs/services/web/nginx/
        # header indispenssable pour connaitre le client reel
        proxy_set_header Host $host;
        # nginx sait qui a ete appeler
        proxy_set_header X-Real-ip $remote_addr;
        # nginx recoit la vrai ip du client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # il garde la trace de chaine des adresse ip s'il y a eu plusieurs proxy
        proxy_set_header X-Forwarded-Proto $scheme;
        # nginx sait qu'on est en https meme si la requete interne est faite en http
    }

    location ~ \.php$ { #pointe vers le conteneur wordpress
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;

    }

    location ~ /\. {
        deny all; #bloque l'acces aux fichiers caches
    }
    # The parameter is a "regular expression" matching all URIs start with "."
    # https://nginx.org/en/docs/beginners_guide.html
    # exemple:
    # location ~ \.(gif|jpg|png)$
    # prend tout les fichiers qui finissent pas .gif, .jpg, .png
}
