#SPDX-License-Identifier: MIT-0
---
# tasks file for setup_inception
- name: install make
  ansible.builtin.apt:
    name: make
    state: latest
  become: true

- name: create volumes
  # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/file_module.html#ansible-collections-ansible-builtin-file-module
  ansible.builtin.file:
    path: /home/{{ deploy_user }}/data/{{ item }}
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0755'
  loop:
    - wordpress
    - mariadb

- name: Copy requirements folder
  ansible.builtin.copy:
    src: ../../../../srcs/requirements/
    dest: /home/{{ deploy_user }}/var/www/cloud-1/requirements/
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0755'
  become: true

# - name: Copy Makefile
#   ansible.builtin.copy:
#     src: ../../../../srcs/Makefile
#     dest: /home/{{ deploy_user }}/var/www/cloud-1/Makefile
#     owner: "{{ deploy_user }}"
#     group: "{{ deploy_user }}"
#     mode: '0755'

- name: Render Docker Compose configuration
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/{{ deploy_user }}/var/www/cloud-1/docker-compose.yml
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0644'

- name: copy .env chiffre
  ansible.builtin.copy:
    src: ../files/.env
    dest: /home/{{ deploy_user }}/var/www/cloud-1/.env
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0600'
  become: true