#SPDX-License-Identifier: MIT-0
---
# tasks file for install_docker
# https://blog.stephane-robert.info/docs/conteneurs/moteurs-conteneurs/docker/installation/
- name: updated packets
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: install curl, certificate and gnup
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificate
      - gnup
    state: latest
  become: true

- name: add GPG key

- name: add repository docker

- name: Install docker engine
  # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true

- name: start docker
  # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/systemd_service_module.html#ansible-collections-ansible-builtin-systemd-service-module
  ansible.builtin.systemd_service:
    name: docker
    state: started
  become: true
