; 10.171.60.136
; ip adress of the servers that we want to manage
[webservers]
; localhost ansible_connection=local ansible_user=root
10.171.60.136 ansible_ssh_private_key_file=~/.ssh/id_ed25519
# 51.159.166.173 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519
; URL : https://portedesaintcloud.duckdns.org
