#SPDX-License-Identifier: MIT-0
---
# tasks file for firewall

- name: install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true
  become: true

# ! ouvrir le 22 AVANT d'activer ufw, sinon on perd la connexion ssh
- name: allow ssh, http and https
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
  become: true

- name: deny all other incoming traffic by default
  community.general.ufw:
    default: deny
    direction: incoming
  become: true

- name: enable ufw
  community.general.ufw:
    state: enabled
  become: true
# https://docs.ansible.com/projects/ansible/latest/collections/community/general/ufw_module.html
