#? faire un clean qui arrete tout et supprimer le dossier cloud-1
---

- name: clean user_deploy space
  hosts: webservers
  remote_user: root
  become: true

  tasks:
# ! a voir apres test mais peut etre faut il verifier que le user et cloud-1 existe avant de faire tout ca
  - name: down the docker compose and clear
    community.docker.docker_compose_v2:
# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_compose_v2_module.html
      project_src: /home/{{ deploy_user }}/var/www/cloud-1
      state: absent
      remove_images: all
      remove_volumes: true

  - name: remove volumes folders
    ansible.builtin.file:
      path: /home/{{deploy_user}}/data/{{ item }}
      state: absent
    loop:
      - wordpress
      - mariadb

  - name: remove cloud-1 folder
    ansible.builtin.file:
      path: /home/{{deploy_user}}/var/www/cloud-1
      state: absent

  - name: remove user_deploy account
    ansible.builtin.user:
      name: "{{ deploy_user }}"
      state: absent
      remove: true