#? faire le make clean qui arrete tout et supprimer le dossier cloud-1
---

- name: clean all cloud-1
  hosts: webservers
  become: true

  tasks:
  - name: make clean for inception
    ansible.builtin.command:
      chdir: /home/{{deploy_user}}//var/www/cloud-1
      args:
        cmd: make clean
        remove: /var/www/cloud-1/Makefile

  - name: rm volumes
    ansible.builtin.file:
      path: /home/{{deploy_user}}/data/{{ item }}
      state: absent
    loop:
      - wordpress
      - mariadb

  - name: rm cloud-1 folder
    ansible.builtin.file:
      path: /home/{{deploy_user}}/var/www/cloud-1
      state: absent

#! think to erase deploy_user
#! supp make for idempotence