#? faire le make clean qui arrete tout et supprimer le dossier cloud-1
---

- name: creation User
  hosts: webservers
  remote_user: root
  become: true

  tasks:
  - name: down the docker compose
    community.docker.docker_compose_v2:
      state: absent

# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_compose_v2_module.html
  - name: erase stoped containeurs

  - name: remove volumes

  - name: rm volumes
    ansible.builtin.file:
      path: /home/{{deploy_user}}/data/{{ item }}
      state: absent
    loop:
      - wordpress
      - mariadb

  - name: rm cloud-1 folder
    ansible.builtin.file:
      path: /home/{{deploy_user}}/var/www/cloud-1
      state: absent

#! think to erase deploy_user
#! supp make for idempotence