# installer les logiciels, creer les dossiers et lancer le make
---

- name: deploy cloud-1
  hosts: webservers
  become: true
  roles:
  - update_packages
  - install_docker
  - setup_inception
  - run_services