# installer les logiciels, creer les dossiers et lancer le make
---
- name: creation User
  hosts: webservers
  become: true
  roles:
  - base


- name: deploy cloud-1
  hosts: webservers
  remote_user: jarvis
  roles:
  - setup_inception
  - install_docker
  - run_services
  #! penser a mettre 'become true' pour les actions qui meritent 'sudo'